name: Build API Code
on: 
  workflow_run:
    workflows: ["Increment Version"]
    types:
      - completed

jobs:
  build-apis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

    - name: Create build branch
      run: |
          git checkout -b build-apis
          git push --set-upstream origin build-apis

    - name: Remove UI code
      run: |
          rm -rf services/PennyUI

    - name: Compile typescript and remove unused files
      run: |
          npm i typescript
          rm -rf package-lock.json
          tsc
          mv Dockerfile-ic Dockerfile
          rm -rf node_modules .github .gitignore Dockerfile-ui Dockerfile-data tsconfig.json lerna.json README.md
          rm -rf $(find . -type f | grep "babel\.config\.js")
          rm -rf $(find . -type f | grep "\.ts")
          rm -rf scripts
          git add .
          git commit -m 'Auto: Compile Typescript'
          git push