name: Create tag
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [merged]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

    # Have to create a new branch so JS files don't end up in master
    - name: Create release branch
      run: |
          git checkout -b release
          git push --set-upstream origin release

    - name: Compile typescript
      run: |
          npm i typescript
          tsc
          git add .
          git commit -m 'Auto: Compile Typescript'
          git push

    - name: Create Tag
      run: |
          VERSION=$(grep version package.json | awk -F \" '{print $4}')
          npm version patch
          git push origin --tags

    - name: Delete release branch
      run: |
          git checkout master
          git branch -D release
          git push origin --delete release

    - name: Increment version on master
      run: |
        npm --no-git-tag-version version patch
        git add package.json
        git commit -m "Auto version increment"
        git push